apiVersion: membership.github.jet.crossplane.io/v1alpha1
kind: Membership
metadata:
  name: zntestjoakim
  annotations:
    email: joakim.hansson@zeronorth.com
    crossplane.io/external-name: 0north:zntestjoakim
spec:
  deletionPolicy: Orphan
  forProvider:
    role: member
    username: zntestjoakim
  providerConfigRef:
    name: github-provider-config
