//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentBranchPolicyObservation) DeepCopyInto(out *DeploymentBranchPolicyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentBranchPolicyObservation.
func (in *DeploymentBranchPolicyObservation) DeepCopy() *DeploymentBranchPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DeploymentBranchPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentBranchPolicyParameters) DeepCopyInto(out *DeploymentBranchPolicyParameters) {
	*out = *in
	if in.CustomBranchPolicies != nil {
		in, out := &in.CustomBranchPolicies, &out.CustomBranchPolicies
		*out = new(bool)
		**out = **in
	}
	if in.ProtectedBranches != nil {
		in, out := &in.ProtectedBranches, &out.ProtectedBranches
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentBranchPolicyParameters.
func (in *DeploymentBranchPolicyParameters) DeepCopy() *DeploymentBranchPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DeploymentBranchPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEnvironment) DeepCopyInto(out *RepositoryEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEnvironment.
func (in *RepositoryEnvironment) DeepCopy() *RepositoryEnvironment {
	if in == nil {
		return nil
	}
	out := new(RepositoryEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEnvironmentList) DeepCopyInto(out *RepositoryEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEnvironmentList.
func (in *RepositoryEnvironmentList) DeepCopy() *RepositoryEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(RepositoryEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEnvironmentObservation) DeepCopyInto(out *RepositoryEnvironmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEnvironmentObservation.
func (in *RepositoryEnvironmentObservation) DeepCopy() *RepositoryEnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryEnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEnvironmentParameters) DeepCopyInto(out *RepositoryEnvironmentParameters) {
	*out = *in
	if in.DeploymentBranchPolicy != nil {
		in, out := &in.DeploymentBranchPolicy, &out.DeploymentBranchPolicy
		*out = make([]DeploymentBranchPolicyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Reviewers != nil {
		in, out := &in.Reviewers, &out.Reviewers
		*out = make([]ReviewersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitTimer != nil {
		in, out := &in.WaitTimer, &out.WaitTimer
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEnvironmentParameters.
func (in *RepositoryEnvironmentParameters) DeepCopy() *RepositoryEnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryEnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEnvironmentSpec) DeepCopyInto(out *RepositoryEnvironmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEnvironmentSpec.
func (in *RepositoryEnvironmentSpec) DeepCopy() *RepositoryEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEnvironmentStatus) DeepCopyInto(out *RepositoryEnvironmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEnvironmentStatus.
func (in *RepositoryEnvironmentStatus) DeepCopy() *RepositoryEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewersObservation) DeepCopyInto(out *ReviewersObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewersObservation.
func (in *ReviewersObservation) DeepCopy() *ReviewersObservation {
	if in == nil {
		return nil
	}
	out := new(ReviewersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewersParameters) DeepCopyInto(out *ReviewersParameters) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.TeamsRefs != nil {
		in, out := &in.TeamsRefs, &out.TeamsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TeamsSelector != nil {
		in, out := &in.TeamsSelector, &out.TeamsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewersParameters.
func (in *ReviewersParameters) DeepCopy() *ReviewersParameters {
	if in == nil {
		return nil
	}
	out := new(ReviewersParameters)
	in.DeepCopyInto(out)
	return out
}
